export const AnimalList =[
    {
      id: 1,
      name: "Lion",
      species: "Panthera leo",
      family: "Felidae",
      habitat: "Grasslands and Savannas",
      place_of_found: "Africa",
      diet: "Carnivore",
      description: "The lion is a large and powerful wild cat known for its majestic appearance and social behavior.",
      weight_kg: 190,
      height_cm: 120,
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/1200px-020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg"
    },
    {
      id: 2,
      name: "Elephant",
      species: "Loxodonta africana",
      family: "Elephantidae",
      habitat: "Savannas, Grasslands, and Forests",
      place_of_found: "Africa, Asia",
      diet: "Herbivore",
      description: "The elephant is the largest land animal on Earth and is known for its intelligence and long trunk.",
      weight_kg: 6000,
      height_cm: 300,
      image: "https://cdn.britannica.com/02/152302-050-1A984FCB/African-savanna-elephant.jpg"
    },
    {
      id: 3,
      name: "Tiger",
      species: "Panthera tigris",
      family: "Felidae",
      habitat: "Forests, Grasslands, and Swamps",
      place_of_found: "Asia",
      diet: "Carnivore",
      description: "The tiger is a powerful predator with striking orange fur and black stripes.",
      weight_kg: 250,
      height_cm: 100,
      image: "https://th-thumbnailer.cdn-si-edu.com/zyik7KJtkSuYCfVOHNyj5KcYLO0=/800x600/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/1d/10/1d102878-7750-49f4-bced-1809c4d7e8ea/tiger.jpg"
    },
    {
      id: 4,
      name: "Kangaroo",
      species: "Macropus",
      family: "Macropodidae",
      habitat: "Forests, Grasslands, and Deserts",
      place_of_found: "Australia",
      diet: "Herbivore",
      description: "Kangaroos are marsupials known for their powerful hind legs and pouches.",
      weight_kg: 85,
      height_cm: 150,
      image: "https://media.istockphoto.com/id/183360956/photo/kangaroo-and-joey.jpg?s=612x612&w=0&k=20&c=NK-ByN4U23hCiBXqQbeiwuVbqL5yHBWhpitA5HF3CIs="
    },
    {
      id: 5,
      name: "Gorilla",
      species: "Gorilla beringei",
      family: "Hominidae",
      habitat: "Forests and Mountains",
      place_of_found: "Africa",
      diet: "Herbivore",
      description: "Gorillas are large and powerful primates known for their intelligence and social structure.",
      weight_kg: 180,
      height_cm: 160,
      image: "https://cdn.britannica.com/79/20279-050-ECDF21A7/mountain-gorilla-Virunga-National-Park-Democratic-Republic.jpg"
    },
    {
      id: 6,
      name: "Polar Bear",
      species: "Ursus maritimus",
      family: "Ursidae",
      habitat: "Arctic Region",
      place_of_found: "Arctic",
      diet: "Carnivore",
      description: "Polar bears are large carnivorous mammals adapted to life in the Arctic and primarily feed on seals.",
      weight_kg: 500,
      height_cm: 130,
      image: "https://cdn.dnaindia.com/sites/default/files/2024/09/22/2653237-image-2024-09-22t075223.607.jpg?im=FitAndFill=(1200,900)"
    },
    {
      id: 7,
      name: "Koala",
      species: "Phascolarctos cinereus",
      family: "Phascolarctidae",
      habitat: "Eucalyptus Forests",
      place_of_found: "Australia",
      diet: "Herbivore",
      description: "Koalas are arboreal marsupials known for their love of eucalyptus leaves.",
      weight_kg: 12,
      height_cm: 60,
      image: "https://d1jyxxz9imt9yb.cloudfront.net/medialib/2188/image/s768x1300/DR_2020-03-01_EastLismore-NSW-AU_Bushfires-FriendsOfTheKoala-KoalasInRehab_StaceyHedman-5D_0344_reduced.jpg"
    },
    {
      id: 8,
      name: "Giraffe",
      species: "Giraffa camelopardalis",
      family: "Giraffidae",
      habitat: "Savannas and Grasslands",
      place_of_found: "Africa",
      diet: "Herbivore",
      description: "Giraffes are the tallest land animals and have long necks and legs.",
      weight_kg: 800,
      height_cm: 550,
      image: "https://i.natgeofe.com/n/f4d64d53-07ce-4933-a76e-1d405eec3473/giraffe_thumb.JPG"
    },
    {
      id: 9,
      name: "Panda",
      species: "Ailuropoda melanoleuca",
      family: "Ursidae",
      habitat: "Bamboo Forests",
      place_of_found: "China",
      diet: "Herbivore",
      description: "Pandas are bears known for their distinctive black and white markings and love for bamboo.",
      weight_kg: 85,
      height_cm: 90,
      image: "https://media.istockphoto.com/id/1195743934/vector/cute-panda-character-vector-design.jpg?s=612x612&w=0&k=20&c=J3ht-bKADmsXvF6gFIleRtfJ6NGhXnfIsrwlsUF8w80="
    },
    {
      id: 10,
      name: "Cheetah",
      species: "Acinonyx jubatus",
      family: "Felidae",
      habitat: "Grasslands and Savannas",
      place_of_found: "Africa",
      diet: "Carnivore",
      description: "Cheetahs are the fastest land animals and have slender bodies built for speed.",
      weight_kg: 50,
      height_cm: 80,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXWP6uhmBAIBmH-VcimnvfjFNuMhhSawGN0g&s"
    }
  ]